### ISSUE TITLE
WebSocket4Net method not found

### ISSUE THREAD

**Issue by vnorbix** [skrusty/AsterNET.ARI#50]
I created a new .NET console project. When I installed AsterNET.ARI from Nuget and tried to run the bridge sample, I got a runtime exception on `ActionClient.Connect();`.

```
Method not found: 'Void WebSocket4Net.WebSocket..ctor(System.String, System.String, System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.String, System.String, WebSocket4Net.WebSocketVersion, System.Net.EndPoint)'.
```

What can be the problem? I tried this with a .NET 4.5 console project, AsterNET.ARI is the latest (1.2).

**Comment by skrusty** [comment]
Yeah, it's a problem with the nuget package, it's installing the wrong version of the dependency. It should be
<dependency id="WebSocket4Net" version="0.15.0-beta6" />

Try manually updating this from nuget package manager.

**Comment by pavelbunkov4517** [comment]
which version of dependencies should be installed?

**Comment by skrusty** [comment]
0.15.0-beta6 or above.

I am looking to update the nuget package today.

**Comment by joelkallman** [comment]
I'm using AsterNET.ARI 1.2.1 in a fresh .NET console project and am getting the following error: 

`Could not load file or assembly 'WebSocket4Net, Version=0.15.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

Is this related to the issue above?

**Comment by skrusty** [comment]
I will look at this next week, this should have been fixed in the latest version.

What version of the .net runtime are you using?

**Comment by joelkallman** [comment]
I'm using .NET Framework 4.6.1 and I tried to recreate it in a project using .NET Framework 4.5.2. Both versions raise the same exception. Thanks for looking at this! If there's any other tests that I can do, I'd be happy to do so.

**Comment by stevoinco** [comment]
Same issue here, running framework 4.6.1. I was able to get around it by manually (re)installing dependencies.

**Comment by ftfunk** [comment]
@stevoinco did you installed all dependencies manually ?

**Comment by vnorbix** [comment]
This one is still not fixed, I still get the same error as @stevoinco and @joelkallman. I'm compiling the dll for myself at the moment, but I want to remove custom dll so I looked into this.

By default in nuget WebSocket 0.15.0 is installed, when I run my app it complains that it doesn't find 0.15.0.**0** of the dll. But the actual dll version exists next to the exe is 0.15.0.**9**. If I try to update websocket to the latest version in nuget it's 0.15.2, then my app complains that it doesn't find the same version as before, 0.15.0.**0**. Why is that? Because I updated to version 0.15.2, actual dll version next to the exe is 0.15.2.11 as expected, but it still tries to reference 0.15.0.**0** at runtime.

**Comment by sbiaudet** [comment]
+1

I've the same problem

**Comment by norcis** [comment]
Same problem too.

**Comment by anastasiya1kovalenko** [comment]
+1

**Comment by KenDFish** [comment]
+1

**Comment by Xandir150** [comment]
+1

**Comment by nikriaz** [comment]
+1

**Comment by ianfoulds** [comment]
This is still a problem with a new project started today. I've tried 4.5 and 4.6.1, WebSocket4Net versions 0.15.0 & 0.15.2 and it get the same error all the time:
`System.IO.FileLoadException: 'Could not load file or assembly 'WebSocket4Net, Version=0.15.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'`

**Comment by shawty** [comment]
If this is the same issue as I reported in issue number 64 (I've just closed it) [https://github.com/skrusty/AsterNET.ARI/issues/64]

Then it should now now be an issue, and I would recommend closing this one too.

**Comment by Muhammad-Shoaib-092** [comment]
Issue is not yet resolved completely, it still generate the same error when used in web services

**Comment by shawty** [comment]
I'm no longer having problems with this, but I have moved to .NET 6 now rather than the legacy framework.
